name: pipeline
on:
  push:
    branches:
      - main

permissions:
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: setup-bun 
        uses: oven-sh/setup-bun@v2

      - name: test
        run: |
          bun install

          bun test test
  build-and-publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: setup-bun 
        uses: oven-sh/setup-bun@v2
        with:
          registry-url: 'https://registry.npmjs.org'

      - name: build
        run: |
          bun install
          bun build:lib

      - name: publish
        run: bun publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
